imports:
  - path: bigquery_dataset.py
    name: bigquery_dataset.py
  - path: bigquery_table.py
    name: bigquery_table.py

resources:
  - name: pubsub-billing-alerts
    type: pubsub.py
    properties:
      topic: billing-alerts

  - name: billing_dataset
    type: bigquery_dataset.py
    properties:
      name: billing
      location: EU

  - name: budget_table
    type: bigquery_table.py
    properties:
      name: budget
      datasetId: $(ref.billing_dataset.datasetId)
      schema:
        - name: createdAt
          type: TIMESTAMP
          mode: REQUIRED
        - name: costAmount
          type: NUMERIC
          mode: REQUIRED
        - name: budgetAmount
          type: NUMERIC
          mode: REQUIRED
        - name: budgetName
          type: STRING
          mode: REQUIRED
        - name: threshold
          type: NUMERIC
          mode: REQUIRED
        - name: budgetId
          type: STRING
          mode: REQUIRED

  - name: slack-notifications-billing
    type: cloud_function.py
    properties:
      region: europe-west1
      entryPoint: subscribe
      runtime: nodejs8
      triggerTopic: projects/tme-chrome/topics/$(ref.pubsub-billing-alerts.name)
      sourceRepository:
        repositoryUrl: https://source.developers.google.com/p/tme-chrome/r/tme-chrome
        sourcePath: /billing-alerts/cf
        branch: master