#@ load("@ytt:data", "data")

#@ def bucket():
#@   return 'gs://' + data.values.bucket_function + '/billing-alert.zip'
#@ end

imports:
  - path: ../bigquery_dataset.py
    name: bigquery_dataset.py
  - path: ../bigquery_table.py
    name: bigquery_table.py
  - path: ../cloud_function.py
    name: cloud_function.py
  - path: ../upload.py
    name: upload.py
  - path: ../pubsub.py
    name: pubsub.py
  - path: ../../fn-notif-billing/index.js
  - path: ../../fn-notif-billing/package.json

resources:
  - name: pubsub-billing-alerts
    type: pubsub.py
    properties:
      topic: #@ data.values.topic_name

  - name: billing_dataset
    type: bigquery_dataset.py
    properties:
      name: #@ data.values.dataset_name
      location: #@ data.values.dataset_location

  - name: budget_table
    type: bigquery_table.py
    properties:
      name: #@ data.values.table_name
      datasetId: $(ref.billing_dataset.datasetId)
      schema:
        - name: createdAt
          type: TIMESTAMP
          mode: REQUIRED
        - name: costAmount
          type: NUMERIC
          mode: REQUIRED
        - name: budgetAmount
          type: NUMERIC
          mode: REQUIRED
        - name: budgetName
          type: STRING
          mode: REQUIRED
        - name: threshold
          type: NUMERIC
          mode: REQUIRED
        - name: budgetId
          type: STRING
          mode: REQUIRED

  - name: slack-notifications-billing
    type: cloud_function.py
    properties:
      region: #@ data.values.region
      entryPoint: notifySlack
      runtime: nodejs8
      environmentVariables:
        BOTTOKEN: #@ data.values.slack_webhook
        CHANNEL: #@ data.values.slack_channel
        DATASET: #@ data.values.dataset_name
        DATASET_LOCATION: #@ data.values.dataset_location
        TABLE: #@ data.values.table_name
      triggerTopic: $(ref.pubsub-billing-alerts.topicName)
      localUploadPath: ../../fn-notif-billing/
      sourceArchiveUrl: #@ bucket()
      region_bucket: #@ data.values.bucket_region