imports:
- path: ../cloud_function.py
  name: cloud_function.py
- path: ../upload.py
  name: upload.py
- path: ../../fn-delta-billing/index.js
- path: ../../fn-delta-billing/package.json
resources:
- name: slash-delta-billing
  type: cloud_function.py
  properties:
    region: europe-west1
    entryPoint: diffBilling
    runtime: nodejs8
    environmentVariables:
      DATASET: billing
      DATASET_LOCATION: EU
      TABLE: budget
      BILLING_ID: 0037AB-CA715E-359E3F
    localUploadPath: ../../fn-delta-billing/
    sourceArchiveUrl: gs://billing-functions-training-190916/slash-delta-billing.zip
    region_bucket: europe-west1
