imports:
- path: ../cloud_function.py
  name: cloud_function.py
- path: ../upload.py
  name: upload.py
- path: ../../fn-current-billing/index.js
- path: ../../fn-current-billing/package.json
resources:
- name: slash-current-billing
  type: cloud_function.py
  properties:
    region: europe-west1
    entryPoint: getCurrentBilling
    runtime: nodejs8
    environmentVariables:
      DATASET: billing
      DATASET_LOCATION: EU
      TABLE: budget
      BILLING_ID: 0037AB-CA715E-359E3F
    localUploadPath: ../../fn-current-billing/
    sourceArchiveUrl: gs://billing-functions-training-190916/slash-current-billing.zip
    region_bucket: europe-west1
